targets:
  $default:
    builders:
      # Auto Route - hanya untuk root app_router
      auto_route_generator:auto_route_generator:
        options:
          inputs:
            - "package:packages/features/onboarding/presentation/**"
            - "package:login_presentation/**"
            - "lib/**"
          generate_for:
            - "lib/router/app_router.dart"
      
      # Injectable - default behavior, no custom config needed
      # Each package will use its own build.yaml if needed

