name: flutter_modular_clean_architecture

scripts:
  # Bootstrap semua packages (install dependencies)
  bootstrap:
    run: dart tool/bootstrap.dart
    description: Install dependencies in all packages

  # Build runner di semua packages sekaligus
  build:
    run: dart tool/build.dart
    description: Run build_runner build in all packages

  # Build runner dengan watch mode
  build:watch:
    run: dart tool/build.dart --watch
    description: Run build_runner watch in all packages

  # Clean generated files
  build:clean:
    run: dart tool/build.dart --clean
    description: Run build_runner clean in all packages

  # Clean semua packages
  clean:
    run: find packages -name "pubspec.yaml" -exec sh -c 'cd "$(dirname "{}")" && flutter clean' \;
    description: Run flutter clean in all packages

  # Analyze semua packages
  analyze:
    run: find packages -name "pubspec.yaml" -exec sh -c 'cd "$(dirname "{}")" && flutter analyze' \;
    description: Run flutter analyze in all packages

  # Format semua dart files
  format:
    run: dart format .
    description: Format all Dart files

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.24.0"
